from typing import Optional, List, Dict, Any, Union
from pydantic import BaseModel, Field

# -------------------------------------------------------------
# Generic & Utility Response Schemas
# -------------------------------------------------------------
class MessageResponse(BaseModel):
    message: str = Field(..., description="Status or confirmation message", example="Operation completed successfully.")

class StatusOkResponse(BaseModel):
    status: str = Field("ok", description="Status confirmation", example="ok")

# -------------------------------------------------------------
# Customer & Segmentation Schemas
# -------------------------------------------------------------
class CustomerResponse(BaseModel):
    id: int = Field(..., description="Unique customer identifier", example=1)
    name: str = Field(..., description="Customer full name", example="John Doe")
    total_spend: float = Field(..., description="Cumulative customer expenditure in INR", example=1250.00)
    segment: str = Field(..., description="Behavioral customer segment ('Premium Customer', 'Regular Customer', 'New Customer')", example="Premium Customer")

# -------------------------------------------------------------
# Vendor Catalog & Product Schemas
# -------------------------------------------------------------
class ProductDetailResponse(BaseModel):
    id: int = Field(..., description="Unique product identifier", example=1)
    name: str = Field(..., description="Product display name", example="Pro Wireless Headphones X2")
    category: str = Field(..., description="Product category", example="Electronics")
    price: float = Field(..., description="Unit price in INR", example=149.99)
    stock: int = Field(..., description="Available inventory stock quantity", example=50)
    image_url: Optional[str] = Field(None, description="Image URL of the product", example="https://images.unsplash.com/photo-1505740420928-5e560c06d30e")
    description: Optional[str] = Field(None, description="Detailed product description", example="Experience high-fidelity audio with active noise cancellation.")

# -------------------------------------------------------------
# Analytics & Reports Schemas
# -------------------------------------------------------------
class SalesTrendDataPoint(BaseModel):
    label: str = Field(..., description="Time interval label (e.g. date, week, or month)", example="2026-09-12")
    sales: float = Field(..., description="Aggregated sales amount in INR", example=450.00)
    orders: int = Field(..., description="Count of orders completed in interval", example=3)

class SalesTrendResponse(BaseModel):
    labels: List[str] = Field(..., description="Time interval labels for chart X-axis", example=["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])
    data: List[float] = Field(..., description="Revenue values for chart Y-axis", example=[150.0, 300.0, 0.0, 450.0, 200.0, 600.0, 350.0])
    label: str = Field(..., description="Chart dataset series label", example="Daily Revenue ($)")
    tooltips: Optional[List[str]] = Field(None, description="Hover tooltip text for each data point", example=["Mon (2026-09-07)", "Tue (2026-09-08)"])

# -------------------------------------------------------------
# AI Services Schemas
# -------------------------------------------------------------
class AIQueryRequest(BaseModel):
    question: str = Field(..., min_length=1, description="Natural language analytical business question", example="What was my best selling product this week?")

class AIQueryResponse(BaseModel):
    status: str = Field(..., description="Execution status ('success' or 'error')", example="success")
    answer: Optional[str] = Field(None, description="Natural language analytical insight generated by Gemini", example="Your top selling product this week was the Pro Wireless Headphones X2 with ₹1,200 in total sales.")
    sql: Optional[str] = Field(None, description="Generated and sanitized read-only MySQL query executed against the database", example="SELECT p.name AS product_name, SUM(t.amount) AS total_sales FROM transactions t JOIN products p ON t.product_id = p.id WHERE t.vendor_email = 'vendor@gmail.com' GROUP BY p.name ORDER BY total_sales DESC LIMIT 5")
    data: Optional[List[Dict[str, Any]]] = Field(None, description="Raw query execution results from MySQL")
    message: Optional[str] = Field(None, description="Error or security alert message if query execution was halted")

class ShoppingAssistantRequest(BaseModel):
    question: str = Field(..., min_length=1, description="Product recommendation question in English, Tamil, or Tanglish", example="Show me wireless headphones under 200")

class CatalogProduct(BaseModel):
    id: int = Field(..., description="Product ID", example=1)
    name: str = Field(..., description="Product name", example="Pro Wireless Headphones X2")
    category: str = Field(..., description="Product category", example="Electronics")
    price: float = Field(..., description="Product price in INR", example=149.99)
    stock: int = Field(..., description="Available inventory stock", example=50)
    description: str = Field(..., description="Product description")
    image_url: Optional[str] = Field("", description="Product image URL")
    vendor_email: str = Field(..., description="Vendor email who owns the product")

class ShoppingAssistantResponse(BaseModel):
    status: str = Field(..., description="Query result status ('success', 'not_found', or 'error')", example="success")
    answer: Optional[str] = Field(None, description="Grounded product recommendation in the user's inquiry language", example="I recommend the Pro Wireless Headphones X2 at ₹149.99. It offers active noise cancellation and 40 hours of battery life. This recommendation is based on the products currently available in the catalog.")
    matched_products: List[Dict[str, Any]] = Field(default_factory=list, description="List of catalog products retrieved via lexical and multilingual RAG matching")
    message: Optional[str] = Field(None, description="Error message if processing failed")

# -------------------------------------------------------------
# Transactions & Real-Time Sync Schemas
# -------------------------------------------------------------
class TransactionCreateResponse(BaseModel):
    status: str = Field("success", description="Transaction status", example="success")
    transaction_id: int = Field(..., description="Generated transaction ID", example=101)
    vendor_email: str = Field(..., description="Vendor email associated with purchased product", example="vendor@gmail.com")
    product_id: int = Field(..., description="Product ID purchased", example=1)
    product_name: str = Field(..., description="Product name purchased", example="Pro Wireless Headphones X2")
    quantity: int = Field(..., description="Quantity purchased", example=2)
    amount: float = Field(..., description="Total transaction amount in INR", example=299.98)

class VerifySeedingResponse(BaseModel):
    status: str = Field(..., description="Seeding operation status ('success' or 'error')", example="success")
    message: str = Field(..., description="Summary message of seeded operations", example="Successfully created new sample sales order for vendor 'vendor@gmail.com'.")
    new_order: Optional[Dict[str, Any]] = Field(None, description="Created order metadata")
    updated_metrics: Optional[Dict[str, Any]] = Field(None, description="Recalculated vendor sales totals")
    real_time_sync: Optional[str] = Field(None, description="Real-time WebSocket event status", example="Broadcasted over WebSocket to Vendor Dashboard")
    traceback: Optional[str] = Field(None, description="Error stack trace if operation failed")

# -------------------------------------------------------------
# System & Diagnostic Schemas
# -------------------------------------------------------------
class ColumnInfo(BaseModel):
    name: str = Field(..., description="Column field name", example="email")
    type: str = Field(..., description="Database column type", example="VARCHAR(150)")
    nullable: bool = Field(..., description="Whether column accepts NULL values", example=False)
    default: Optional[str] = Field(None, description="Default column value")
    primary_key: Union[int, bool] = Field(..., description="Primary key indicator", example=1)

class DebugDBResponse(BaseModel):
    status: str = Field(..., description="Schema inspection status ('success' or 'error')", example="success")
    columns: Optional[List[ColumnInfo]] = Field(None, description="List of columns discovered in vendors table")
    message: Optional[str] = Field(None, description="Error message if introspection failed")
